name: Preview Build
on:
  push:
    branches:
      - feature/external-download
      - preview
  pull_request:
    branches:
      - feature/external-download
      - preview
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-preview:
    name: Build & Preview Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Code Analysis (Detekt)
        run: ./gradlew detekt --no-daemon

      - name: Get Current Version
        id: get_version
        run: |
          GRADLE_FILE="app/build.gradle.kts"
          CURRENT_VN=$(grep "versionName =" $GRADLE_FILE | sed 's/.*"\(.*\)".*/\1/')
          echo "VERSION=$CURRENT_VN" >> $GITHUB_ENV
          echo "CURRENT_VN=$CURRENT_VN"

      - name: Build Debug APK
        run: ./gradlew assembleDebug -Pinclude-telemetry=false -Penable-updater=false -PabiList=arm64-v8a --no-daemon
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Rename APK
        run: |
          VERSION="${{ env.VERSION }}"
          cd app/build/outputs/apk/debug/
          find . -name "*universal*" -delete
          for f in *arm64-v8a*.apk; do
            mv "$f" "AniZen-v$VERSION-preview-$f"
          done

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AniZen-Preview-v${{ env.VERSION }}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
